<img src="Screenshot 2026-08-26 at 7.15.43 PM.png">
<img src="Screenshot 2026-08-26 at 7.06.28 PM.png">
<img src="Screenshot 2026-08-26 at 7.08.39 PM.png">
<img src="Screenshot 2026-08-26 at 7.09.02 PM.png">

## PART 3: DATA PREPROCESSING
#### Step 1: Load Dataset

In [30]:
import pandas as pd

# Load CSV file
df = pd.read_csv('/content/100_Unique_QA_Dataset.csv')

df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

##### just for understanding

In [6]:
text="What is the cApital of France?"
print(text.lower())
print(text.replace("?",""))
print(text.split())

what is the capital of france?
What is the cApital of France
['What', 'is', 'the', 'cApital', 'of', 'France?']

### Step 2: Tokenization
Tokenization means splitting text into individual words.

In [ ]:
def tokenize(text):
 # Convert every letter in text to lowercase
 text = text.lower() 
 # Remove question marks and inverted commas
 text = text.replace('?', '') #replace ? with nothing
 text = text.replace(',', '')
 # Split by spaces # return list of words
 return text.split()

# Example
sentence = "What is the capital of France?"
tokens = tokenize(sentence)
print(tokens)

['what', 'is', 'the', 'capital', 'of', 'france']

### Step 3: Build Vocabulary
Vocabulary is a dictionary mapping each unique word to a unique index

vocab -> { word1:1 ,word2 : 2, word3: 3 ,   ...}

In [32]:
# Start with UNKNOWN token (index 0)
vocab = {'<UNK>':0}

In [ ]:
def build_vocab(row): # sends row by row

  # Tokenize both question and answer
  tokenized_question = tokenize(row['question']) #list of words of that row in question feature
  tokenized_answer = tokenize(row['answer']) #list of words of that row in answer feature

  # Merge both lists
  merged_tokens = tokenized_question + tokenized_answer

  for token in merged_tokens:
    # add new words to vocabulary
    if token not in vocab:
      vocab[token] = len(vocab)

  return vocab

In [34]:
df.apply(build_vocab, axis=1)

0     {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
1     {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
2     {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
3     {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
4     {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
                            ...
85    {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
86    {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
87    {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
88    {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
89    {'<UNK>': 0, 'what': 1, 'is': 2, 'the': 3, 'ca...
Length: 90, dtype: object

#### df has not changed though (no inplace=True done),we are only updating vocab dictionary

In [35]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 "'to": 12,
 'kill': 13,
 'a': 14,
 "mockingbird'": 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 "'1984'": 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299792458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 "'starry": 130,
 "night'": 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'to': 143,
 'step': 144,
 'moon': 145,
 'armstrong': 146,
 'main': 147,
 'ingredient': 148,
 'guacamole': 149,
 'avocado': 150,
 'sides': 151,
 'does': 152,
 'hexagon': 153,
 'have': 154,
 '6': 155,
 'china': 156,
 'yuan': 157,
 "'pride": 158,
 'and': 159,
 "prejudice'": 160,
 'jane-austen': 161,
 'iron': 162,
 'fe': 163,
 'hardest': 164,
 'natural': 165,
 'substance': 166,
 'diamond': 167,
 'continent': 168,
 'by': 169,
 'area': 170,
 'asia': 171,
 'president': 172,
 'states': 173,
 'george-washington': 174,
 'bird': 175,
 'its': 176,
 'ability': 177,
 'mimic': 178,
 'sounds': 179,
 'parrot': 180,
 'longest-running': 181,
 'animated': 182,
 'tv': 183,
 'show': 184,
 'simpsons': 185,
 'vaticancity': 186,
 'most': 187,
 'moons': 188,
 'saturn': 189,
 "'romeo": 190,
 "juliet'": 191,
 'shakespeare': 192,
 "earth's": 193,
 'atmosphere': 194,
 'nitrogen': 195,
 'bones': 196,
 'adult': 197,
 'human': 198,
 'body': 199,
 '206': 200,
 'metal': 201,
 'liquid': 202,
 'at': 203,
 'room': 204,
 'temperature': 205,
 'mercury': 206,
 'russia': 207,
 'moscow': 208,
 'electricity': 209,
 'benjamin-franklin': 210,
 'second-largest': 211,
 'land': 212,
 'color': 213,
 'ripe': 214,
 'banana': 215,
 'yellow': 216,
 'month': 217,
 '28': 218,
 'days': 219,
 'common': 220,
 'february': 221,
 'study': 222,
 'living': 223,
 'organisms': 224,
 'called': 225,
 'biology': 226,
 'home': 227,
 'great': 228,
 'wall': 229,
 'bees': 230,
 'collect': 231,
 'from': 232,
 'flowers': 233,
 'nectar': 234,
 'opposite': 235,
 "'day'": 236,
 'night': 237,
 'south': 238,
 'korea': 239,
 'seoul': 240,
 'bulb': 241,
 'edison': 242,
 'humans': 243,
 'breathe': 244,
 'survival': 245,
 'oxygen': 246,
 '144': 247,
 '12': 248,
 'pyramids': 249,
 'giza': 250,
 'egypt': 251,
 'sea': 252,
 'creature': 253,
 'eight': 254,
 'arms': 255,
 'octopus': 256,
 'holiday': 257,
 'celebrated': 258,
 'december': 259,
 '25': 260,
 'christmas': 261,
 'yen': 262,
 'legs': 263,
 'spider': 264,
 'sport': 265,
 'uses': 266,
 'net': 267,
 'ball': 268,
 'hoop': 269,
 'basketball': 270,
 'kangaroos': 271,
 'female': 272,
 'minister': 273,
 'uk': 274,
 'margaretthatcher': 275,
 'fastest': 276,
 'animal': 277,
 'cheetah': 278,
 'periodic': 279,
 'table': 280,
 'spain': 281,
 'madrid': 282,
 'closest': 283,
 'sun': 284,
 'father': 285,
 'computers': 286,
 'charlesbabbage': 287,
 'mexico': 288,
 'mexicocity': 289,
 'colors': 290,
 'rainbow': 291,
 'musical': 292,
 'instrument': 293,
 'black': 294,
 'white': 295,
 'keys': 296,
 'piano': 297,
 'americas': 298,
 '1492': 299,
 'christophercolumbus': 300,
 'disney': 301,
 'character': 302,
 'long': 303,
 'nose': 304,
 'grows': 305,
 'it': 306,
 'when': 307,
 'lying': 308,
 'pinocchio': 309,
 'directed': 310,
 'movie': 311,
 "'titanic'": 312,
 'jamescameron': 313,
 'superhero': 314,
 'also': 315,
 'dark': 316,
 'knight': 317,
 'batman': 318,
 'brasilia': 319,
 'fruit': 320,
 'king': 321,
 'fruits': 322,
 'mango': 323,
 'eiffel': 324,
 'tower': 325}

In [36]:
len(vocab)

326

### Step 4: Convert Text to Numerical Indices from our existing vocab

In [ ]:
# convert words to numerical indices during prediction from our existing vocabulary
def text_to_indices(text, vocab):

  indexed_text = []

  for token in tokenize(text):

    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>']) # use UNK token

  return indexed_text

In [38]:
question="What is campusx"
indices=text_to_indices(question, vocab)
print(f"Question: {question}")
print(f"Indices: {indices}")

Question: What is campusx
Indices: [1, 2, 0]

### PART 4: CUSTOM DATASET AND DATALOADER

In [39]:
import torch
from torch.utils.data import Dataset, DataLoader

In [40]:
class QADataset(Dataset):

  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return len(self.df)

  def __getitem__(self, index):
    # gets question and answer as text
    question=self.df.iloc[index]['question']
    answer=self.df.iloc[index]["answer"]
    numerical_question = text_to_indices(question, self.vocab)
    numerical_answer = text_to_indices(answer, self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

### Create dataset and dataloader

In [41]:
dataset = QADataset(df, vocab)
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

# Test loading
question_tensor,answer_tensor=dataset[0]
print(f"Question indices: {question_tensor}")
print(f"Answer indices: {answer_tensor}")

Question indices: tensor([1, 2, 3, 4, 5, 6])
Answer indices: tensor([7])

In [42]:
for question, answer in dataloader:
  print(question, answer[0])

tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([52])
tensor([[ 42, 137,   2, 227, 143,   3, 228, 229]]) tensor([156])
tensor([[ 78,  79, 290,  81,  19,  14, 291]]) tensor([85])
tensor([[ 42, 252, 253, 118, 254, 255]]) tensor([256])
tensor([[ 10,  11, 190, 159, 191]]) tensor([192])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([36])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([116])
tensor([[ 10,  29, 130, 131]]) tensor([132])
tensor([[ 42,   2,   3, 211, 137, 169, 212, 170]]) tensor([113])
tensor([[ 42, 137,   2,  62,  39,   3, 324, 325]]) tensor([6])
tensor([[  1,   2,   3, 181, 182, 183, 184]]) tensor([185])
tensor([[ 42,  86,  87, 243, 244,  19,  39, 245]]) tensor([246])
tensor([[  1,   2,   3, 222,   5, 223, 224, 225]]) tensor([226])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([49])
tensor([[  1,   2,   3,  33,  34,   5, 247]]) tensor([248])
tensor([[ 42, 292, 293, 118, 294, 159, 295, 296]]) tensor([297])
tensor([[  1,   2,   3,   4,   5, 288]]) tensor([289])
tensor([[ 42, 257,   2, 258,  83, 259, 260]]) tensor([261])
tensor([[ 10,  11, 158, 159, 160]]) tensor([161])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([134])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([262])
tensor([[  1,   2,   3,   4,   5, 207]]) tensor([208])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([91])
tensor([[ 10,   2,  62,  63,   3, 285,   5, 286]]) tensor([287])
tensor([[  1,   2,   3, 147,  86,  19, 193, 194]]) tensor([195])
tensor([[ 42, 175,   2,  62,  39, 176, 177, 143, 178, 179]]) tensor([180])
tensor([[  1,   2,   3, 235,   5, 236]]) tensor([237])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([58])
tensor([[  1,   2,   3,   4,   5, 281]]) tensor([282])
tensor([[ 42,  18,   2,   3, 283, 143,   3, 284]]) tensor([206])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([16])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([36])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([23])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([95])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[ 10, 140,   3, 141, 172,   5,   3,  70, 173]]) tensor([174])
tensor([[ 42, 201,   2,  14, 202, 203, 204, 205]]) tensor([206])
tensor([[ 10,  96,   3, 104, 241]]) tensor([242])
tensor([[10, 96,  3, 97]]) tensor([98])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([85])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([128])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([41])
tensor([[ 78,  79, 151, 152,  14, 153, 154]]) tensor([155])
tensor([[ 10,  75, 111]]) tensor([112])
tensor([[10, 29,  3, 30, 31]]) tensor([32])
tensor([[ 10,  75, 209]]) tensor([210])
tensor([[ 78,  79, 196,  81,  19,   3, 197, 198, 199]]) tensor([200])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([61])
tensor([[  1,   2,   3,  37,  38,  39, 162]]) tensor([163])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([100])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([136])
tensor([[10, 75, 76]]) tensor([77])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([186])
tensor([[  1,   2,   3,   4,   5, 238, 239]]) tensor([240])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([72])
tensor([[ 10, 310,   3, 311, 312]]) tensor([313])
tensor([[  1,  87, 230, 231, 232, 233]]) tensor([234])
tensor([[ 42, 314,   2, 315,  62,  63,   3, 316, 317]]) tensor([318])
tensor([[ 42, 265, 266,  14, 267, 268, 159, 269]]) tensor([270])
tensor([[  1,   2,   3, 164, 165, 166,  83,  84]]) tensor([167])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([53])
tensor([[ 42,   2,   3, 276, 212, 277]]) tensor([278])
tensor([[ 42, 301, 302, 118,  14, 303, 304, 159, 305, 306, 307, 308]]) tensor([309])
tensor([[  1,   2,   3, 147, 148,  19, 149]]) tensor([150])
tensor([[  1,   2,   3,  69,   5, 156]]) tensor([157])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([121])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([65])
tensor([[ 42, 320,   2,  62,  63,   3, 321,   5, 322]]) tensor([323])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([68])
tensor([[ 42, 137,   2, 138,  39, 176, 271]]) tensor([99])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([106])
tensor([[ 10, 140,   3, 141, 272,  93, 273,   5,   3, 274]]) tensor([275])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([124])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([74])
tensor([[  1,   2,   3, 141, 117,  83,   3, 279, 280]]) tensor([121])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([110])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([28])
tensor([[ 42, 137, 118,   3, 249,   5, 250]]) tensor([251])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([319])
tensor([[  1,   2,   3, 213,   5,  14, 214, 215]]) tensor([216])
tensor([[ 42, 101,   2,   3,  17]]) tensor([102])
tensor([[ 42, 217, 118, 218, 219,  19,  14, 220,  43]]) tensor([221])
tensor([[ 10, 140,   3, 141, 142, 143, 144,  83,   3, 145]]) tensor([146])
tensor([[ 10,  75,   3, 298,  19, 299]]) tensor([300])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([114])
tensor([[ 42,  18, 118,   3, 187, 188]]) tensor([189])
tensor([[ 78,  79, 263, 152,  14, 264, 154]]) tensor([36])
tensor([[ 42, 168,   2,   3,  17, 169, 170]]) tensor([171])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([54])

## PART 5:RNN MODEL ARCHITECTURE

<img src="Screenshot 2026-08-26 at 7.44.26 PM.png">

No, you **cannot** use `nn.Sequential` here directly, and here's why:

## The Problem

`nn.Sequential` only works when:
1. Each layer takes **exactly one input** and produces **exactly one output**
2. Data flows linearly from one layer to the next

But `nn.RNN` returns **two things**: `(output, hidden_state)`, while your next layer `nn.Linear` only expects the hidden state.

In [43]:
import torch.nn as nn

In [51]:
class SimpleRNN(nn.Module):

  def __init__(self, vocab_size):
    super().__init__()

    #Embedding layer: converts word indices,each word to vectors of 50 dim embedding
    self.embedding = nn.Embedding(vocab_size, embedding_dim=50)

    #RNN layer:processes sequence with memory
    #batch_first=True means input shape is (batch,seq_len,features)
    self.rnn = nn.RNN(50, 64, batch_first=True)

    # Fully connected layer:maps to vocabulary size
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))

    return output

In [52]:
## for understanding of embedding,each word to vectors of 50 embedding dim
print(dataset[0])
print(dataset[0][0])

x=nn.Embedding(len(vocab),embedding_dim=50)
x(dataset[0][0]).shape

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))
tensor([1, 2, 3, 4, 5, 6])

torch.Size([6, 50])

## PART6 : TRAINING THE MODEL

In [53]:
# hyperparameters
learning_rate = 0.001
epochs = 20

# Initialize model
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = SimpleRNN(len(vocab))
model.to(device)

#Loss function for multiclass classification
criterion = nn.CrossEntropyLoss()

#Optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

## Training Loop

In [55]:
for epoch in range(epochs):
  model.train()
  total_loss=0

  for question, answer in dataloader:
    question = question.to(device)
    answer = answer.to(device)

    #clear gradients
    optimizer.zero_grad()

    #Forward pass
    predictions=model(question) #Shape:(1,vocab_size)

    #Calculate loss
    #answer is tensor([index]),need to ensure its the right shape

    loss=criterion(predictions,answer[0])

    #Backward pass
    loss.backward()

    #Update weights
    optimizer.step()

    #Accumulate loss
    total_loss+=loss.item()

  print(f"Epoch {epoch+1}/{epochs},loss:{total_loss:.4f}")

Epoch 1/20,loss:522.5291
Epoch 2/20,loss:456.2611
Epoch 3/20,loss:380.1803
Epoch 4/20,loss:316.0171
Epoch 5/20,loss:263.1076
Epoch 6/20,loss:214.5475
Epoch 7/20,loss:169.6770
Epoch 8/20,loss:132.0185
Epoch 9/20,loss:101.8471
Epoch 10/20,loss:78.7520
Epoch 11/20,loss:61.4596
Epoch 12/20,loss:48.4362
Epoch 13/20,loss:39.0174
Epoch 14/20,loss:31.9121
Epoch 15/20,loss:26.4530
Epoch 16/20,loss:21.9738
Epoch 17/20,loss:18.6027
Epoch 18/20,loss:15.9170
Epoch 19/20,loss:13.8697
Epoch 20/20,loss:12.0188

## PART 7 : MAKING PREDICTIONS

In [56]:
import torch.nn.functional

In [ ]:
def predict(model, question, threshold=0.5):

  # step 1: convert question to numbers/indices
  numerical_question = text_to_indices(question, vocab)

  # step2:convert to tensor and add batch dimension
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # step 3:Get model predictions(logits)
  output = model(question_tensor)

  # step 4: convert logits to probabilities using softmax
  probs = torch.nn.functional.softmax(output, dim=1)

  # step5 : find max probability and its  index
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")

  print(list(vocab.keys())[index])

In [ ]:
predict(model, "What is the largest planet in our solar system?")

jupiter

In [ ]:
list(vocab.keys())[7]

'paris'